CREATE OR REPLACE VIEW V_SALAIRE_EMP_PROCHE AS
SELECT 
    e.EMPNO,
    e.ENAME,
    e.JOB,
    e.MGR,
    e.HIREDATE,
    e.SAL,
    e.COMM,
    e.DEPTNO,
    COALESCE(h.DATE_SAL, e.HIREDATE) AS DATE_SAL,
    COALESCE(h.MONTANT, e.SAL) AS ANCIEN_MONTANT
FROM emp e
LEFT JOIN histosal h ON e.EMPNO = h.EMPNO
ORDER BY e.EMPNO ASC, h.DATE_SAL DESC;



---COMPARER LA DATE
SELECT 1 FROM dual WHERE TRUNC(TO_DATE('26-OCT-2025', 'DD-MON-YYYY')) >= TRUNC(SYSDATE);